# Generated by Django 5.0.6 on 2026-01-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={},
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.CheckConstraint(check=models.Q(('role', 'Administrateur')), name='single_admin_role'),
        ),
    ]
