# Generated by Django 5.0.6 on 2026-01-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_utilisateur_options_alter_utilisateur_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('alimentaire', 'Alimentaire'), ('animal', 'Animaux'), ('equipement', 'Équipements')], max_length=20, verbose_name='Catégorie')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('desc', models.TextField(verbose_name='Description')),
                ('price', models.CharField(max_length=50, verbose_name='Prix')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
