# Generated by Django 5.0.6 on 2026-01-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('alimentaire', 'Alimentaire'), ('animal', 'Animal'), ('equipement', 'Équipements')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
